build: off

clone_folder: c:\github.com\nukosuke\terraform-provider-zendesk

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

cache:
  - '%LocalAppData%\go-build'
  - '%GOPATH%\pkg\mod'

stack: go 1.11.6

install:
  - sed -i.bak '/github.com\/hashicorp\/go-getter/d' go.sum # dirty workaround for #76
  - go mod download

before_test:
  - go vet ./...

test_script:
  - go test ./...
