build: off

image: Visual Studio 2022

clone_folder: c:\github.com\nukosuke\terraform-provider-zendesk

environment:
  GOPATH: c:\gopath

cache:
  - '%LocalAppData%\go-build -> go.sum'
  - '%GOPATH%\pkg\mod -> go.sum'

stack: go 1.17.7

install:
  - go version
  - go mod download

before_test:
  - go vet ./...

test_script:
  - go test -v ./...
