# frozen_string_literal: true

# Generate reversed_locale_types.go from public locale list from API

require 'json'
require 'uri'
require 'net/http'
require 'erb'

uri = URI.parse('https://d3v-terraform-provider.zendesk.com/api/v2/locales/public.json')
req = Net::HTTP::Get.new(uri)
res = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
  http.request(req)
end

if res.is_a? Net::HTTPSuccess
  data = JSON.parse(res.body)
  puts ERB.new(DATA.read).result(binding)
else
  abort "failed to fetch from locale API: #{res.body.inspect}"
end

__END__
package zendesk

// DO NOT EDIT
// This file is generated by tools/generate_locale_type_dict.rb
// 
// <%= data['count'] %> locales are supported

var reversedLocaleTypes = map[string]int64{<% data['locales'].each_with_index do |locale, idx| %>
	"<%= locale['locale'] %>": <%= locale['id'] %>,<% end %>
}

var localeTexts = []string{<% data['locales'].each_with_index do |locale, idx| %>
"<%= locale['locale'] %>",<% end %>
}
